local objects = {
    {
        id = 4,
        name = "Coin",
        type = "",
        shape = "rectangle",
        x = 64.8954,
        y = 223.422,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 49,
        visible = true,
        properties = {}
      },
      {
        id = 6,
        name = "Coin",
        type = "",
        shape = "rectangle",
        x = 96.4472,
        y = 223.422,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 49,
        visible = true,
        properties = {}
      },
      {
        id = 8,
        name = "Coin",
        type = "",
        shape = "rectangle",
        x = 127.999,
        y = 223.422,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 49,
        visible = true,
        properties = {}
      },
      {
        id = 9,
        name = "Coin",
        type = "",
        shape = "rectangle",
        x = 334.717,
        y = 247.678,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 49,
        visible = true,
        properties = {}
      },
      {
        id = 10,
        name = "Coin",
        type = "",
        shape = "rectangle",
        x = 354.301,
        y = 247.678,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 49,
        visible = true,
        properties = {}
      },
      {
        id = 11,
        name = "Coin",
        type = "",
        shape = "rectangle",
        x = 374.973,
        y = 247.678,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 49,
        visible = true,
        properties = {}
      },
      {
        id = 12,
        name = "Coin",
        type = "",
        shape = "rectangle",
        x = 395.645,
        y = 247.678,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 49,
        visible = true,
        properties = {}
      },
      {
        id = 13,
        name = "Coin",
        type = "",
        shape = "rectangle",
        x = 384.765,
        y = 229.182,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 49,
        visible = true,
        properties = {}
      },
      {
        id = 14,
        name = "Coin",
        type = "",
        shape = "rectangle",
        x = 385.853,
        y = 266.174,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 49,
        visible = true,
        properties = {}
      },
      {
        id = 15,
        name = "Coin",
        type = "",
        shape = "rectangle",
        x = 561.019,
        y = 203.07,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 49,
        visible = true,
        properties = {}
      },
      {
        id = 16,
        name = "Coin",
        type = "",
        shape = "rectangle",
        x = 543.612,
        y = 187.838,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 49,
        visible = true,
        properties = {}
      },
      {
        id = 17,
        name = "Coin",
        type = "",
        shape = "rectangle",
        x = 528.38,
        y = 172.607,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 49,
        visible = true,
        properties = {}
      },
      {
        id = 18,
        name = "Coin",
        type = "",
        shape = "rectangle",
        x = 479.42,
        y = 77.9513,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 49,
        visible = true,
        properties = {}
      },
      {
        id = 19,
        name = "Coin",
        type = "",
        shape = "rectangle",
        x = 432.636,
        y = 77.9513,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 49,
        visible = true,
        properties = {}
      },
      {
        id = 20,
        name = "Coin",
        type = "",
        shape = "rectangle",
        x = 527.292,
        y = 77.9513,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 49,
        visible = true,
        properties = {}
      },
      {
        id = 21,
        name = "Coin",
        type = "",
        shape = "rectangle",
        x = 591.483,
        y = 93.1832,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 49,
        visible = true,
        properties = {}
      },
      {
        id = 22,
        name = "Coin",
        type = "",
        shape = "rectangle",
        x = 608.891,
        y = 109.503,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 49,
        visible = true,
        properties = {}
      },
      {
        id = 23,
        name = "Coin",
        type = "",
        shape = "rectangle",
        x = 626.299,
        y = 124.735,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 49,
        visible = true,
        properties = {}
      },
      {
        id = 24,
        name = "Coin",
        type = "",
        shape = "rectangle",
        x = 356.477,
        y = 142.143,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 49,
        visible = true,
        properties = {}
      },
      {
        id = 25,
        name = "Coin",
        type = "",
        shape = "rectangle",
        x = 374.973,
        y = 142.143,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 49,
        visible = true,
        properties = {}
      },
      {
        id = 26,
        name = "Coin",
        type = "",
        shape = "rectangle",
        x = 393.469,
        y = 142.143,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 49,
        visible = true,
        properties = {}
      },
      {
        id = 27,
        name = "Gem",
        type = "",
        shape = "rectangle",
        x = 434.812,
        y = 145.087,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 54,
        visible = true,
        properties = {}
      },
      {
        id = 28,
        name = "Gem",
        type = "",
        shape = "rectangle",
        x = 324.925,
        y = 80.1273,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 54,
        visible = true,
        properties = {}
      },
      {
        id = 29,
        name = "Gem",
        type = "",
        shape = "rectangle",
        x = 457.66,
        y = 51.8395,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 54,
        visible = true,
        properties = {}
      },
      {
        id = 30,
        name = "Gem",
        type = "",
        shape = "rectangle",
        x = 503.356,
        y = 51.8395,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 54,
        visible = true,
        properties = {}
      },
      {
        id = 31,
        name = "Gem",
        type = "",
        shape = "rectangle",
        x = 240.062,
        y = 255.294,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 54,
        visible = true,
        properties = {}
      },
      {
        id = 32,
        name = "Gem",
        type = "",
        shape = "rectangle",
        x = 781.882,
        y = 109.503,
        width = 16,
        height = 16,
        rotation = 0,
        gid = 54,
        visible = true,
        properties = {}
      }
}

return objects